name: Format

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install ruff
        run: pip install ruff

      - name: Check formatting
        run: ruff format --check .
